import json
import os

notebook_path = r"c:\Users\Martin.Mueller\projects\llm_engineering\week7\solution\Week_7_Day_3_RL_TRAINING_REFACTORED.ipynb"

# Define the cells
cells = [
    {
        "cell_type": "markdown",
        "metadata": {"id": "Header"},
        "source": [
            "# The Price Is Right - Week 7 - Day 3 (RL Training)\n",
            "\n",
            "## Training with Reinforcement Learning (PPO)\n",
            "\n",
            "In this notebook, we will train the model using Proximal Policy Optimization (PPO) to directly minimize the pricing error.\n",
            "\n",
            "**Goal**: Refine a standard LLM to become a price prediction expert using Reinforcement Learning.\n",
            "\n",
            "**Reward Function**: `Reward = -|Predicted Price - True Price|`\n",
            "\n",
            "### Setup\n",
            "If using `LITE_MODE=True`, a T4 GPU is sufficient. For full training, use an A100 or L4.",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "InstallLibs"},
        "outputs": [],
        "source": [
            "# 1. Install Libraries\n",
            "# AGGRESSIVE DEPENDENCY RESOLUTION\n",
            "# We must ensure numpy<2.0 and compatible torch/transformers versions to avoid binary incompatibility.\n",
            "\n",
            "import os\n",
            "import sys\n",
            "\n",
            "def install_dependencies():\n",
            '    print("Installing dependencies... This may take a minute.")\n',
            "    \n",
            "    # 1. Uninstall critical packages to avoid conflicts\n",
            "    !pip uninstall -y numpy torch transformers trl peft accelerate bitsandbytes\n",
            "    \n",
            "    # 2. Install numpy first (pinned)\n",
            '    !pip install "numpy<2.0"\n',
            "    \n",
            "    # 3. Install Torch (pinned to stable 2.4.1 to match typical Colab drivers and avoid 2.5.0+ issues with old numpy)\n",
            '    !pip install "torch==2.4.1" "torchvision==0.19.1" "torchaudio==2.4.1" --index-url https://download.pytorch.org/whl/cu121\n',
            "    \n",
            "    # 4. Install ecosystem libraries\n",
            "    # We pin transformers slightly back to be safe with TRL 0.9.6\n",
            '    !pip install "transformers==4.44.2" "datasets>=2.19.0" "accelerate==0.34.2" "peft==0.12.0" "bitsandbytes==0.43.3" "trl==0.9.6" "wandb"\n',
            "\n",
            '    print("Dependencies installed.")\n',
            "    \n",
            "    # 5. Check if restart is needed (Colab preloads numpy)\n",
            '    if "google.colab" in sys.modules:\n',
            '        print("Restarting Colab runtime to apply changes...")\n',
            "        import IPython\n",
            "        app = IPython.Application.instance()\n",
            "        app.kernel.do_shutdown(True)\n",
            "\n",
            "try:\n",
            "    import trl\n",
            "    import numpy\n",
            '    if numpy.__version__ >= "2.0.0":\n',
            '        print(f"Detected Numpy {numpy.__version__}. Reinstalling...")\n',
            "        install_dependencies()\n",
            "except ImportError:\n",
            "    install_dependencies()\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "Imports"},
        "outputs": [],
        "source": [
            "import os\n",
            "import re\n",
            "import torch\n",
            "import math\n",
            "import wandb\n",
            "from tqdm import tqdm\n",
            "from datetime import datetime\n",
            "from getpass import getpass\n",
            "from huggingface_hub import login\n",
            "import numpy as np\n",
            "\n",
            'print(f"Numpy Version: {np.__version__}")\n',
            "if np.__version__ >= '2.0.0':\n",
            '    raise RuntimeError("Numpy version is >= 2.0.0. Please Restart Session and run the install cell again.")\n',
            "\n",
            "import transformers\n",
            "from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig\n",
            "from peft import LoraConfig, get_peft_model\n",
            "from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer\n",
            "from datasets import load_dataset\n",
            "\n",
            "# Verify versions\n",
            'print(f"PyTorch: {torch.__version__}")\n',
            'print(f"Transformers: {transformers.__version__}")\n',
            'print(f"TRL: {trl.__version__}")',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "Config"},
        "outputs": [],
        "source": [
            "# 2. Configuration\n",
            "\n",
            'BASE_MODEL = "meta-llama/Llama-3.2-3B"\n',
            'PROJECT_NAME = "price-rl"\n',
            'HF_USER = "Rodan009" # Update/Verify your HF username if needed\n',
            "\n",
            "LITE_MODE = True\n",
            "\n",
            'DATA_USER = "Rodan009"\n',
            'DATASET_NAME = f"{DATA_USER}/items_prompts_lite" if LITE_MODE else f"{DATA_USER}/items_prompts_full"\n',
            "\n",
            'RUN_NAME = f"{datetime.now():%Y-%m-%d_%H.%M.%S}"\n',
            "if LITE_MODE:\n",
            '    RUN_NAME += "-lite"\n',
            "    \n",
            'PROJECT_RUN_NAME = f"{PROJECT_NAME}-{RUN_NAME}"\n',
            'HUB_MODEL_NAME = f"{HF_USER}/{PROJECT_RUN_NAME}"\n',
            "\n",
            "# LoRA Config\n",
            "QUANT_4_BIT = True\n",
            "LORA_R = 32 if LITE_MODE else 64\n",
            "LORA_ALPHA = LORA_R * 2\n",
            "LORA_DROPOUT = 0.05\n",
            "\n",
            "# PPO Config\n",
            "LEARNING_RATE = 1.41e-5\n",
            "BATCH_SIZE = 64 if LITE_MODE else 128\n",
            "MINI_BATCH_SIZE = 8 if LITE_MODE else 16\n",
            "GRADIENT_ACCUMULATION_STEPS = 1\n",
            "MAX_NEW_TOKENS = 12\n",
            "PPO_EPOCHS = 1\n",
            "\n",
            "capability = torch.cuda.get_device_capability()\n",
            "use_bf16 = capability[0] >= 8 # Use bf16 on Ampere+ (A100, L4)\n",
            "\n",
            "LOG_TO_WANDB = True",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "Logins"},
        "outputs": [],
        "source": [
            "# 3. Logins\n",
            "if 'HF_TOKEN' in os.environ:\n",
            "    hf_token = os.environ['HF_TOKEN']\n",
            "else:\n",
            "    try:\n",
            "        from google.colab import userdata\n",
            "        hf_token = userdata.get('HF_TOKEN')\n",
            "    except:\n",
            '        hf_token = getpass("Hugging Face Token: ")\n',
            "login(hf_token, add_to_git_credential=True)\n",
            "\n",
            "if LOG_TO_WANDB:\n",
            "    if 'WANDB_API_KEY' not in os.environ:\n",
            "        try:\n",
            "            from google.colab import userdata\n",
            "            os.environ[\"WANDB_API_KEY\"] = userdata.get('WANDB_API_KEY')\n",
            "        except:\n",
            "            pass\n",
            "\n",
            "    if 'WANDB_API_KEY' not in os.environ:\n",
            '        os.environ["WANDB_API_KEY"] = getpass("WandB API Key: ")\n',
            "    wandb.login()\n",
            '    os.environ["WANDB_PROJECT"] = PROJECT_NAME\n',
            '    os.environ["WANDB_LOG_MODEL"] = "false"',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "LoadModel"},
        "outputs": [],
        "source": [
            "# 4. Load Model & Tokenizer\n",
            "\n",
            'print("Loading Base Model...")\n',
            "if QUANT_4_BIT:\n",
            "    quant_config = BitsAndBytesConfig(\n",
            "        load_in_4bit=True,\n",
            "        bnb_4bit_use_double_quant=True,\n",
            "        bnb_4bit_compute_dtype=torch.bfloat16 if use_bf16 else torch.float16,\n",
            '        bnb_4bit_quant_type="nf4"\n',
            "    )\n",
            "else:\n",
            "    quant_config = BitsAndBytesConfig(\n",
            "        load_in_8bit=True,\n",
            "        bnb_8bit_compute_dtype=torch.bfloat16 if use_bf16 else torch.float16,\n",
            "    )\n",
            "\n",
            "base_model = AutoModelForCausalLM.from_pretrained(\n",
            "    BASE_MODEL,\n",
            "    quantization_config=quant_config,\n",
            '    device_map="auto",\n',
            "    trust_remote_code=True\n",
            ")\n",
            "\n",
            'print("Applying LoRA...")\n',
            "peft_config = LoraConfig(\n",
            "    r=LORA_R,\n",
            "    lora_alpha=LORA_ALPHA,\n",
            "    lora_dropout=LORA_DROPOUT,\n",
            '    bias="none",\n',
            '    task_type="CAUSAL_LM",\n',
            '    target_modules=["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],\n',
            ")\n",
            "base_model = get_peft_model(base_model, peft_config)\n",
            "\n",
            'print("Wrapping with AutoModelForCausalLMWithValueHead...")\n',
            "# We wrap the PEFT model. TRL handles the value head on top.\n",
            "model = AutoModelForCausalLMWithValueHead(base_model)\n",
            "\n",
            "# Tokenizer\n",
            "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)\n",
            "tokenizer.pad_token = tokenizer.eos_token\n",
            'tokenizer.padding_side = "left"  # Important for generation\n',
            "\n",
            'print("Model Loaded Successfully")',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "DataProcessing"},
        "outputs": [],
        "source": [
            "# 5. Data Processing\n",
            "\n",
            "def extract_price(text):\n",
            "    # Extract first float found in text\n",
            "    if not isinstance(text, str):\n",
            "        return 0.0\n",
            '    match = re.search(r"[-+]?\\d*\\.\\d+|\\d+", text)\n',
            "    return float(match.group()) if match else 0.0\n",
            "\n",
            "def build_dataset(dataset_name, tokenizer):\n",
            '    print(f"Loading dataset: {dataset_name}")\n',
            "    try:\n",
            '        ds = load_dataset(dataset_name, split="train")\n',
            "    except Exception as e:\n",
            "        # Fallback to local if HUB version fails or not found\n",
            '        print(f"Could not load from hub, trying to synthesize for demo: {e}")\n',
            "        from datasets import Dataset\n",
            "        data = [\n",
            '            {"prompt": "What is the price of a banana?", "completion": "The price is $0.50"},\n',
            '            {"prompt": "How much for this car?", "completion": "Price: $25000"}\n',
            "        ] * 10\n",
            "        ds = Dataset.from_list(data)\n",
            "    \n",
            "    def preprocess_function(examples):\n",
            "        new_examples = {\n",
            '            "query": [],\n',
            '            "input_ids": [],\n',
            '            "true_price": []\n',
            "        }\n",
            '        for prompt, completion in zip(examples["prompt"], examples["completion"]):\n',
            '             new_examples["query"].append(prompt)\n',
            "             # Tokenize prompt without special tokens to allow generation continuation\n",
            "             tokenized = tokenizer.encode(prompt, add_special_tokens=False)\n",
            '             new_examples["input_ids"].append(tokenized)\n',
            '             new_examples["true_price"].append(extract_price(completion))\n',
            "\n",
            "        return new_examples\n",
            "\n",
            "    ds = ds.map(preprocess_function, batched=True, remove_columns=ds.column_names)\n",
            '    ds = ds.filter(lambda x: len(x["input_ids"]) < 512)\n',
            '    ds.set_format(type="torch")\n',
            "    return ds\n",
            "\n",
            "dataset = build_dataset(DATASET_NAME, tokenizer)\n",
            'print(f"Dataset loaded: {len(dataset)} examples")\n',
            'print("Sample:", dataset[0])',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "PPOInit"},
        "outputs": [],
        "source": [
            "# 6. Initialize PPO Trainer\n",
            "\n",
            "def collator(data):\n",
            "    # Extract true_prices first\n",
            '    true_prices = [d["true_price"] for d in data]\n',
            "    \n",
            "    # Prepare input batch for padding\n",
            "    # We only care about input_ids and attention_mask (if exists)\n",
            '    model_inputs = [{k: v for k, v in d.items() if k in ["input_ids", "attention_mask"]} for d in data]\n',
            "    \n",
            "    # Pad the inputs\n",
            "    padding_collator = transformers.DataCollatorWithPadding(tokenizer)\n",
            "    batch = padding_collator(model_inputs)\n",
            "    \n",
            "    # Add true_price back\n",
            '    batch["true_price"] = torch.tensor(true_prices)\n',
            "    return batch\n",
            "\n",
            "config = PPOConfig(\n",
            "    learning_rate=LEARNING_RATE,\n",
            "    batch_size=BATCH_SIZE,\n",
            "    mini_batch_size=MINI_BATCH_SIZE,\n",
            "    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,\n",
            "    remove_unused_columns=False,\n",
            "    gradient_checkpointing=True\n",
            ")\n",
            "\n",
            "# We explicitly pass ref_model=None to let TRL handle the reference model (shared weights)\n",
            "ppo_trainer = PPOTrainer(\n",
            "    config=config,\n",
            "    model=model,\n",
            "    ref_model=None,\n",
            "    tokenizer=tokenizer,\n",
            "    dataset=dataset,\n",
            "    data_collator=collator\n",
            ")\n",
            'print("PPO Trainer Initialized")',
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": "TrainingLoop"},
        "outputs": [],
        "source": [
            "# 7. Training Loop\n",
            "\n",
            "generation_kwargs = {\n",
            '    "min_length": -1,\n',
            '    "top_k": 0.0,\n',
            '    "top_p": 1.0,\n',
            '    "do_sample": True,\n',
            '    "pad_token_id": tokenizer.eos_token_id,\n',
            '    "max_new_tokens": MAX_NEW_TOKENS,\n',
            "}\n",
            "\n",
            "if LOG_TO_WANDB:\n",
            "    wandb.init(project=PROJECT_NAME, name=RUN_NAME)\n",
            "\n",
            "save_steps = 20\n",
            "step_count = 0\n",
            "\n",
            'print("Starting Training...")\n',
            "\n",
            "for epoch in range(PPO_EPOCHS):\n",
            '    print(f"Epoch {epoch+1}/{PPO_EPOCHS}")\n',
            "    for batch in tqdm(ppo_trainer.dataloader):\n",
            "        # 1. Prepare Queries\n",
            "        # PPOTrainer expects a list of tensors for queries\n",
            '        query_tensors = [t for t in batch["input_ids"]]\n',
            "        \n",
            "        # 2. Generate Responses\n",
            "        response_tensors = ppo_trainer.generate(\n",
            "            query_tensors,\n",
            "            return_prompt=False,\n",
            "            **generation_kwargs\n",
            "        )\n",
            "        \n",
            '        batch["response"] = [tokenizer.decode(r.squeeze()) for r in response_tensors]\n',
            "        \n",
            "        # 3. Compute Rewards\n",
            "        rewards = []\n",
            "        predicted_prices = []\n",
            "        errors = []\n",
            "        \n",
            '        for response, true_price in zip(batch["response"], batch["true_price"]):\n',
            "            pred_price = extract_price(response)\n",
            "            predicted_prices.append(pred_price)\n",
            "            \n",
            "            # Reward is negative absolute error\n",
            "            error = abs(pred_price - true_price.item())\n",
            "            rewards.append(torch.tensor(-error))\n",
            "            errors.append(error)\n",
            "            \n",
            "        # 4. PPO Step\n",
            "        # Pass tensors directly\n",
            "        stats = ppo_trainer.step(query_tensors, response_tensors, rewards)\n",
            "        \n",
            "        # 5. Logging\n",
            "        if LOG_TO_WANDB:\n",
            "            batch_reward = torch.stack(rewards).mean().item()\n",
            "            avg_error = sum(errors) / len(errors)\n",
            "            \n",
            "            log_data = {\n",
            '                "reward": batch_reward,\n',
            '                "error": avg_error,\n',
            '                "mean_true_price": batch["true_price"].float().mean().item(),\n',
            '                "mean_predicted_price": sum(predicted_prices) / len(predicted_prices),\n',
            "            }\n",
            "            log_data.update(stats)\n",
            "            wandb.log(log_data)\n",
            "            \n",
            "        step_count += 1\n",
            "        if step_count % save_steps == 0:\n",
            '            print(f"Saving checkpoint at step {step_count}...")\n',
            "            ppo_trainer.save_pretrained(PROJECT_RUN_NAME)\n",
            "\n",
            'print("Training Completed.")\n',
            "ppo_trainer.save_pretrained(PROJECT_RUN_NAME)\n",
            'print(f"Model saved to {PROJECT_RUN_NAME}")\n',
            "\n",
            "# Optional: Push to Hub\n",
            "try:\n",
            "    ppo_trainer.model.push_to_hub(HUB_MODEL_NAME)\n",
            '    print(f"Pushed to Hub: {HUB_MODEL_NAME}")\n',
            "except Exception as e:\n",
            '    print(f"Could not push to hub: {e}")\n',
            "\n",
            "if LOG_TO_WANDB:\n",
            "    wandb.finish()",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {"id": "Footer"},
        "source": [
            "## Conclusion\n",
            "\n",
            "We have successfully trained a model to price items using PPO. \n",
            "Check the WandB dashboard to see the Error rate dropping over time!",
        ],
    },
]

notebook = {
    "cells": cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "gpuType": "T4",
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 0,
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=4)
